PATCH http://localhost:3000/api/employee

###
GET http://localhost:3000/api/users/asdfasdf/role


###
PUT http://localhost:3000/api/auth/updatepassword

Content-Type: application/json

{
  "newPassword":"test",
}